### ISSUE TITLE
Change background color of saved video

### ISSUE THREAD

**Issue by neuropil** [robertosannazzaro/motion-heatmap-opencv#3]
This is awesome - thank for you making this code available!

Two quick questions. If I wanted to change the background color of the saved to BW, what would I change in the code - to make the heat images pop out more. Second question, which parameters should we adjust to have the frames apply intensity maps for faster or slower movements. It seems like a heat map is created if the image is static for longer, faster movements have less heat map representation. Thanks!

**Comment by robsannaa** [comment]
Thanks! However, my code is an adaptation of the [Motion Hetmap from Intel](https://github.com/intel-iot-devkit/python-cv-samples/tree/master/examples/motion-heatmap).

I re-arranged their code in order to work with video files.

To change the color to BW you might want to apply a filter on it. You can for example iterate over each frame you will create the video from and apply something like this: `grayImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2GRAY)`. Or you can take the final video and apply the same mask on it.
The heatmap is less sensitive to faster movements, areas where over the time lots of movements happened will be redder, while is there is only one fast movement it will be "less detected".
